# Generated by python-tui-lib/scripts/bundle-tiered-todo.sh — DO NOT EDIT.
# Source: ~/python-tui-lib/tuilib/todo_format.py
"""Canonical TODO.md marker grammar — status + delegation tier.

This module is the single source of truth for how a TODO item's status bracket
is parsed and rendered. Every consumer imports from here rather than carrying
its own regex; see `~/CLAUDE.md` — Delegation for what the tiers mean.

Grammar
-------
    - [<status> <tier>] **Title** — text

Both parts are optional and the tier comes last::

    - [ ]            open, unranked  (legacy + auto-captured deferrals)
    - [T4]           open, tier 4
    - [wip T2]       in progress, tier 2
    - [verify T3]    awaiting verification, tier 3
    - [wip]          in progress, unranked
    - [x]            done

Done lines deliberately carry no tier — the tier is a dispatch input, not a
historical record, and Done lines are already length-capped at ~130 chars.

Tiers
-----
    T0  mechanical lookup                        haiku
    T1  mechanical edit, known recipe            sonnet @ medium
    T2  bounded implementation                   sonnet @ high
    T3  multi-file work against a settled plan   opus   @ medium
    T4  design + implementation                  opus   @ high
    T5  do it yourself, inline — no subagent

An unranked item is treated as `DEFAULT_TIER` so legacy and auto-captured work
is never under-served.

Non-Python consumers keep their own equivalent pattern but must stay in sync
with `TASK_RE` here:

- ``hooks/todo-reminder.sh``      (bash ERE)
- ``scripts/md-to-html.sh``       (inline Python, matches post-bullet text)
- ``~/wald3n.com/scripts/todo-sync/todo_sync.py``  (separate repo)
"""

import re

__all__ = [
    'TASK_RE', 'TIER_RE', 'DEFAULT_TIER', 'TIERS', 'OPEN_STATUSES',
    'AGENT_STAMP_RE', 'Marker',
    'parse_marker', 'render_marker', 'is_open', 'tier_of',
    'strip_agent_stamp', 'agent_of', 'set_agent_stamp',
]


#: Full task line: indent, bullet, status bracket, text.
#: Groups: 1=indent, 2=status (None|x|X|wip|verify), 3=tier (None|T0..T5), 4=text
TASK_RE = re.compile(
    r'^(\s*)[-*] \[\s*(x|X|wip|verify)?\s*(T[0-5])?\s*\]\s+(.+)$'
)

#: Just the tier token, for validation.
TIER_RE = re.compile(r'^T[0-5]$')

#: Live-agent stamp on a `[wip …]` item, e.g. ``<!-- agent:a7a12a1f88b6840b4 -->``.
#: Lets a long run re-message the agent that already holds the context instead
#: of briefing a fresh one. Invisible when rendered, and survives compaction.
AGENT_STAMP_RE = re.compile(r'\s*<!--\s*agent:([A-Za-z0-9_-]+)\s*-->')

#: Tier an unranked item is dispatched at.
DEFAULT_TIER = 'T3'

#: Tier -> (model, effort, agent name). T5 has no agent: it runs inline.
TIERS = {
    'T0': ('haiku',  None,     't0-lookup'),
    'T1': ('sonnet', 'medium', 't1-sonnet-med'),
    'T2': ('sonnet', 'high',   't2-sonnet-high'),
    'T3': ('opus',   'medium', 't3-opus-med'),
    'T4': ('opus',   'high',   't4-opus-high'),
    'T5': (None,     None,     None),
}

#: Statuses that mean "still to do". `None` is a plain `- [ ]`.
OPEN_STATUSES = (None, 'wip', 'verify')


class Marker:
    """A parsed TODO line.

    Attributes:
        indent:  leading whitespace, preserved on re-render
        status:  None | 'wip' | 'verify' | 'x'  ('X' is normalised to 'x')
        tier:    None | 'T0'..'T5'
        text:    everything after the bracket, agent stamp included
    """

    __slots__ = ('indent', 'status', 'tier', 'text')

    def __init__(self, indent='', status=None, tier=None, text=''):
        self.indent = indent
        self.status = status
        self.tier = tier
        self.text = text

    @property
    def done(self):
        return self.status == 'x'

    @property
    def open(self):
        return self.status in OPEN_STATUSES

    @property
    def effective_tier(self):
        """Tier to dispatch at — the explicit one, else DEFAULT_TIER."""
        return self.tier or DEFAULT_TIER

    @property
    def agent(self):
        """Agent id from the `<!-- agent:… -->` stamp, or None."""
        return agent_of(self.text)

    def render(self):
        return render_marker(self.status, self.tier, self.text, self.indent)

    def __repr__(self):
        return (f'Marker(status={self.status!r}, tier={self.tier!r}, '
                f'text={self.text[:40]!r})')


def parse_marker(line):
    """Parse a TODO line into a `Marker`, or return None if it is not one."""
    m = TASK_RE.match(line.rstrip('\n'))
    if not m:
        return None
    indent, status, tier, text = m.groups()
    if status:
        status = status.lower()
    return Marker(indent=indent, status=status, tier=tier, text=text)


def render_marker(status, tier, text, indent=''):
    """Render a status bracket back to a TODO line.

    Empty status *and* empty tier render as `- [ ]` (the legacy open form), so
    round-tripping an unranked item is lossless.
    """
    inner = ' '.join(p for p in (status, tier) if p) or ' '
    return f'{indent}- [{inner}] {text}'


def is_open(line):
    """True if `line` is a task line that still needs doing."""
    m = parse_marker(line)
    return m is not None and m.open


def tier_of(line):
    """Dispatch tier for `line`, or None if it is not a task line."""
    m = parse_marker(line)
    return m.effective_tier if m else None


def agent_of(text):
    """Agent id stamped on `text`, or None."""
    m = AGENT_STAMP_RE.search(text)
    return m.group(1) if m else None


def strip_agent_stamp(text):
    """Remove any `<!-- agent:… -->` stamp, e.g. when moving an item to Done."""
    return AGENT_STAMP_RE.sub('', text).rstrip()


def set_agent_stamp(text, agent_id):
    """Replace (or append) the agent stamp on `text`.

    Passing `agent_id=None` just strips it.
    """
    base = strip_agent_stamp(text)
    if not agent_id:
        return base
    return f'{base}  <!-- agent:{agent_id} -->'
