#!/usr/bin/env bash
# Generated by python-tui-lib/scripts/bundle-tiered-todo.sh — DO NOT EDIT.
# Source: ~/python-tui-lib/scripts/todo-init.sh
# Scaffold a project's TODO.md (and optionally a plan) from the shared templates.
#
# Exists because six skeletons hand-written in one afternoon came out six subtly
# different ways — some with the marker legend, some without, different filler
# text. That is drift being manufactured in real time, which is exactly what the
# rest of this system is trying to stop.
#
# Refuses to clobber an existing non-empty TODO.md. Migrating a legacy file is a
# judgement job, not a template job: use `/todo sweep`, which reorganises the
# content instead of discarding it.
set -euo pipefail

HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
TEMPLATES="$HERE/../templates/todo"

usage() {
    cat <<'EOF'
todo-init.sh — scaffold TODO.md from the shared template

Usage:
  todo-init.sh [options] [DIR]

  DIR              project directory (default: current directory)

Options:
  --plan TOPIC     also scaffold docs/plans/YYYY-MM-DD-<topic>.md from the
                   plan template, and print the TODO line to add for it
  --task           print the Taskfile snippet (todo:lint / todo:stale) to stdout
                   so you can paste or append it
  --force          overwrite an existing TODO.md (destructive; prefer /todo sweep)
  -n, --dry-run    show what would be written, write nothing
  -h, --help       show this help and exit

The project name in the header is derived from the directory name.
An existing non-empty TODO.md is never overwritten without --force — run
`/todo sweep` to migrate a legacy file instead.
EOF
}

DIR="."
PLAN=""
DRY=0
FORCE=0
SHOW_TASK=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)    usage; exit 0 ;;
        --plan)       PLAN="${2:-}"; [[ -n "$PLAN" ]] || { echo "error: --plan needs a topic" >&2; exit 2; }; shift 2 ;;
        --task)       SHOW_TASK=1; shift ;;
        --force)      FORCE=1; shift ;;
        -n|--dry-run) DRY=1; shift ;;
        -*)           echo "error: unknown option: $1" >&2; usage >&2; exit 2 ;;
        *)            DIR="$1"; shift ;;
    esac
done

if [[ "$SHOW_TASK" -eq 1 ]]; then
    cat "$TEMPLATES/Taskfile.todo.yml"
    exit 0
fi

[[ -d "$DIR" ]] || { echo "error: not a directory: $DIR" >&2; exit 2; }
[[ -f "$TEMPLATES/TODO.md" ]] || { echo "error: template missing: $TEMPLATES/TODO.md" >&2; exit 1; }

DIR=$(cd -- "$DIR" && pwd)
PROJECT=$(basename "$DIR")
TODO="$DIR/TODO.md"

# --- TODO.md ---------------------------------------------------------------
if [[ -s "$TODO" && "$FORCE" -eq 0 ]]; then
    echo "todo-init: $TODO already exists and is non-empty — not overwriting." >&2
    echo "  To migrate a legacy file, run '/todo sweep' in that project (it" >&2
    echo "  reorganises the content). Use --force only to discard it." >&2
    exit 1
fi

rendered=$(sed "s|{{PROJECT}}|$PROJECT|g" "$TEMPLATES/TODO.md")

if [[ "$DRY" -eq 1 ]]; then
    echo "--- would write $TODO ---"
    printf '%s\n' "$rendered"
else
    printf '%s\n' "$rendered" > "$TODO"
    echo "todo-init: wrote $TODO"
fi

# --- optional plan ---------------------------------------------------------
if [[ -n "$PLAN" ]]; then
    slug=$(echo "$PLAN" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-' | sed 's/--*/-/g; s/^-//; s/-$//')
    [[ -n "$slug" ]] || { echo "error: --plan topic produced an empty slug" >&2; exit 2; }
    today=$(date -u +%F)
    plan_path="$DIR/docs/plans/$today-$slug.md"
    title="${PLAN^}"   # capitalise first char; bash builtin beats a sed round-trip

    if [[ -e "$plan_path" && "$FORCE" -eq 0 ]]; then
        echo "todo-init: $plan_path already exists — not overwriting." >&2
    elif [[ "$DRY" -eq 1 ]]; then
        echo "--- would write $plan_path ---"
    else
        mkdir -p "$(dirname "$plan_path")"
        sed "s|{{TITLE}}|$title|g" "$TEMPLATES/plan.md" > "$plan_path"
        echo "todo-init: wrote $plan_path"
    fi

    echo
    echo "Add this to ## Open (rank it yourself — ranking is T5, never delegated):"
    echo "  - [ ] **$title** — one-line explanation. [plan](docs/plans/$today-$slug.md)"
fi

# --- next steps ------------------------------------------------------------
if [[ "$DRY" -eq 0 ]]; then
    echo
    echo "Next: add items with /todo, dispatch with /next, check with:"
    echo "  python3 $HERE/todo-lint.py $TODO"
    echo "Wire 'task todo:lint' with: $0 --task >> Taskfile.yml"
fi
