# Generated by python-tui-lib/scripts/bundle-tiered-todo.sh — DO NOT EDIT.
# Source: ~/python-tui-lib/scripts/todo-lint.py
#!/usr/bin/env python3
"""Check a TODO.md against the four-bucket + delegation-tier spec.

The spec lives in `~/.claude/commands/todo.md` ("Format rules"); the marker
grammar lives in `tuilib/todo_format.py`. This is the executable version of
both, so conformance stops being something each session re-derives by hand.

Checks
------
    buckets     the four canonical `##` sections exist, in order
    stray-done  no `[x]` outside `## Done`
    open-rank   every open item in `## Open` carries a tier
    bucket-tier only `## Open` carries tiers; Watch/Parked are plain bullets
    done-form   `- [x] YYYY-MM-DD — [slug] …`, newest first, no tier
    stamp       `<!-- agent:… -->` only on `[wip …]` items
    sections    no unexpected top-level `##` (`## Inbox` is sanctioned)

The auto-captured deferrals block is exempt from every check --
`audit-plan-deferrals.sh` owns it and its items are untriaged by design.

Exit status
-----------
    0   clean (or only warnings, unless --strict)
    1   violations found
    2   usage error

`--fix` applies the mechanical subset only: stripping markers from Watch/Parked
bullets and normalising `[~]` to `[wip]`. It will never assign a tier -- ranking
is T5 and belongs to the orchestrator.
"""

import argparse
import re
import sys
from pathlib import Path

# Works in both layouts: live (`<repo>/scripts/` next to `<repo>/tuilib/`) and
# bundled into the plugin (`<plugin>/scripts/` next to `<plugin>/lib/tuilib/`).
_HERE = Path(__file__).resolve().parent
for _cand in (_HERE.parent, _HERE.parent / "lib", _HERE):
    if (_cand / "tuilib" / "todo_format.py").is_file():
        sys.path.insert(0, str(_cand))
        break
else:
    sys.exit("todo-lint: cannot locate tuilib/todo_format.py")

from tuilib.todo_format import parse_marker  # noqa: E402

BUCKETS = ["Open", "Watch", "Parked", "Done"]
SANCTIONED_EXTRA = {"Inbox"}
MAX_PER_CHECK = 5

#: Per-file opt-out, e.g. `<!-- todo-lint: disable=stray-done,done-form -->`.
#: llvm-mos-65816 keeps ~132 completed entries inline in their milestone
#: sections on purpose — each carries evidence with no linked plan to recover
#: it from — so a blanket stray-done rule would keep that file permanently red
#: and train everyone to ignore the linter.
DIRECTIVE_RE = re.compile(r"<!--\s*todo-lint:\s*disable=([a-z0-9,\- ]+)\s*-->")
DONE_RE = re.compile(r"^- \[x\] (\d{4}-\d{2}-\d{2}|\?{4}-\?{2}-\?{2}) — \[[a-z0-9-]+\] ")
STAMP_RE = re.compile(r"<!--\s*agent:")


class Finding:
    __slots__ = ("level", "check", "line", "msg")

    def __init__(self, level, check, line, msg):
        self.level, self.check, self.line, self.msg = level, check, line, msg

    def __str__(self):
        loc = f":{self.line}" if self.line else ""
        return f"  {self.level:<5} {self.check:<11}{loc:<7} {self.msg}"


def scan(path):
    """Return (findings, lines). Pure — no mutation."""
    text = Path(path).read_text(errors="replace")
    lines = text.splitlines()
    out = []
    section = None
    in_inbox = False
    seen_sections = []
    done_dates = []

    disabled = set()
    for d in DIRECTIVE_RE.findall(text):
        disabled |= {c.strip() for c in d.split(",") if c.strip()}

    def add(level, check, line, msg):
        if check not in disabled:
            out.append(Finding(level, check, line, msg))

    for i, raw in enumerate(lines, 1):
        if "BEGIN auto-captured-deferrals" in raw:
            in_inbox = True
        if "END auto-captured-deferrals" in raw:
            in_inbox = False
            continue

        if raw.startswith("## "):
            word = raw[3:].split("—")[0].split()[0] if len(raw) > 3 else None
            # Legacy files spell it `## DONE`. Classify case-insensitively so a
            # heading-case slip reports as ONE sections finding instead of
            # cascading into hundreds of bogus stray-done errors.
            section = next((b for b in BUCKETS if word and word.lower() == b.lower()), word)
            if section in BUCKETS and word != section:
                add("WARN", "sections", i, f"## {word} should be ## {section}")
            seen_sections.append((i, section))
            continue

        if in_inbox:
            continue

        m = parse_marker(raw)
        if m is None:
            continue

        if m.done and section != "Done":
            add("ERROR", "stray-done", i, f"[x] item outside ## Done (in ## {section})")
        if section == "Open" and m.open and not m.tier:
            add("ERROR", "open-rank", i, "open item has no delegation tier")
        if section in ("Watch", "Parked"):
            add("ERROR", "bucket-tier", i, f"## {section} must be plain bullets — found a marker")
        if section == "Done":
            if m.tier:
                add("ERROR", "done-form", i, "Done line carries a tier; tiers are dispatch inputs")
            if not DONE_RE.match(raw.strip()):
                add("WARN", "done-form", i, "not `- [x] YYYY-MM-DD — [slug] …`")
            d = re.search(r"(\d{4}-\d{2}-\d{2})", raw)
            if d:
                done_dates.append((i, d.group(1)))
        if STAMP_RE.search(raw) and m.status != "wip":
            add("WARN", "stamp", i, "agent stamp on a non-[wip] item; strip it when work ends")

    names = [s for _, s in seen_sections]
    for b in BUCKETS:
        if b not in names:
            add("ERROR", "buckets", 0, f"missing ## {b}")
    present = [n for n in names if n in BUCKETS]
    if present != [b for b in BUCKETS if b in present]:
        add("WARN", "buckets", 0, f"buckets out of canonical order: {' → '.join(present)}")
    for ln, n in seen_sections:
        if n not in BUCKETS and n not in SANCTIONED_EXTRA:
            add("WARN", "sections", ln, f"unexpected top-level ## {n}")

    for (l1, d1), (_, d2) in zip(done_dates, done_dates[1:]):
        if "?" not in d1 and "?" not in d2 and d1 < d2:
            add("WARN", "done-form", l1, f"Done not newest-first ({d1} before {d2})")
            break

    return out, lines


def fix(path, lines):
    """Apply the mechanical subset. Never assigns a tier."""
    section = None
    in_inbox = False
    changed = 0
    for i, raw in enumerate(lines):
        if "BEGIN auto-captured-deferrals" in raw:
            in_inbox = True
        if "END auto-captured-deferrals" in raw:
            in_inbox = False
        if raw.startswith("## "):
            section = raw[3:].split("—")[0].split()[0] if len(raw) > 3 else None
            continue
        if in_inbox:
            continue
        if raw.lstrip().startswith("- [~]"):
            lines[i] = raw.replace("- [~]", "- [wip]", 1)
            changed += 1
            continue
        if section in ("Watch", "Parked"):
            m = parse_marker(raw)
            if m:
                lines[i] = f"{m.indent}- {m.text}"
                changed += 1
    if changed:
        Path(path).write_text("\n".join(lines) + "\n")
    return changed


def main():
    ap = argparse.ArgumentParser(
        description="Check a TODO.md against the four-bucket + tier spec.",
        epilog="Exit 0 clean, 1 violations, 2 usage error.")
    ap.add_argument("paths", nargs="*", default=["TODO.md"],
                    help="TODO.md files to check (default: ./TODO.md)")
    ap.add_argument("--fix", action="store_true",
                    help="apply mechanical fixes (never assigns a tier)")
    ap.add_argument("--strict", action="store_true",
                    help="treat warnings as violations")
    ap.add_argument("--quiet", "-q", action="store_true",
                    help="only report files with findings")
    args = ap.parse_args()

    worst = 0
    for p in args.paths:
        if not Path(p).is_file():
            print(f"{p}: no such file", file=sys.stderr)
            worst = max(worst, 1)
            continue
        findings, lines = scan(p)
        if args.fix:
            n = fix(p, lines)
            if n:
                print(f"{p}: applied {n} mechanical fix(es)")
                findings, _ = scan(p)
        errs = [f for f in findings if f.level == "ERROR"]
        warns = [f for f in findings if f.level == "WARN"]
        if not findings:
            if not args.quiet:
                print(f"{p}: clean")
            continue
        print(f"{p}: {len(errs)} error(s), {len(warns)} warning(s)")
        shown = {}
        for f in findings:
            shown[f.check] = shown.get(f.check, 0) + 1
            if shown[f.check] <= MAX_PER_CHECK:
                print(f)
            elif shown[f.check] == MAX_PER_CHECK + 1:
                rest = sum(1 for g in findings if g.check == f.check) - MAX_PER_CHECK
                print(f"  {'':<5} {f.check:<11}{'':<7} … and {rest} more")
        if errs or (args.strict and warns):
            worst = max(worst, 1)
    return worst


if __name__ == "__main__":
    sys.exit(main())
