#!/usr/bin/env bash
# Generated by python-tui-lib/scripts/bundle-tiered-todo.sh — DO NOT EDIT.
# Source: ~/python-tui-lib/hooks/no-fable-subagent.sh
# PreToolUse[Agent] — Fable is the orchestrator, never a subagent.
#
# Delegation tiers (see ~/CLAUDE.md — Delegation) route work to haiku/sonnet/opus.
# Fable is the model driving the session; spawning it as a subagent burns the most
# expensive context available on work that was explicitly ranked as not needing it.
# T5 means "do it yourself, inline" — not "dispatch a Fable agent".
#
# Matcher is `Agent`, not `Task`: context-mode's pretooluse.mjs rewrites any `Task`
# matcher into `Agent|Task` on the fly, so `Agent` is the stable form.
set -euo pipefail

input=$(cat)
model=$(echo "$input" | jq -r '.tool_input.model // empty')
subtype=$(echo "$input" | jq -r '.tool_input.subagent_type // empty')

if echo "$model $subtype" | grep -qiE 'fable'; then
    printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"Fable is the orchestrator, never a subagent. Rank the task 0-5 and dispatch to its tier agent (t0-lookup, t1-sonnet-med, t2-sonnet-high, t3-opus-med, t4-opus-high), or if it is T5 do it inline yourself. See ~/CLAUDE.md — Delegation."}}'
fi
