#!/usr/bin/env bash
# Generated by python-tui-lib/scripts/bundle-tiered-todo.sh — DO NOT EDIT.
# Source: ~/python-tui-lib/hooks/rank-requires-fable.sh
# PreToolUse[Write|Edit] — only Fable may assign a delegation tier.
#
# Ranking is T5: done inline by the orchestrator, never delegated (see
# ~/CLAUDE.md — Delegation). Two rules were previously enforced only by
# instruction; this makes them mechanical:
#
#   1. Classification runs on Fable. `"model": "fable"` in settings.json sets
#      the session default, but /model can override it at any time, and nothing
#      noticed. Now a non-Fable session is blocked from writing a new tier.
#   2. Classification is never delegated. A subagent's transcript reports its
#      own model (sonnet/opus/haiku), so a tier-writing subagent trips the same
#      check — the "never delegate the classifier" rule becomes enforced rather
#      than merely asked for.
#
# It fires ONLY when an operation would ADD a tier marker to a TODO.md. Moving,
# reformatting, or preserving existing tiers is untouched, so sweep agents that
# re-organise a file without ranking it are unaffected.
#
# Fails OPEN when the model cannot be determined (no transcript, unreadable
# JSONL). This is a workflow guard, not a security boundary — silently blocking
# every TODO.md write because a log was missing would be far worse than missing
# an occasional mis-tiered edit.
set -euo pipefail

usage() {
    cat <<'EOF'
rank-requires-fable.sh — PreToolUse[Write|Edit] guard

Denies any Write/Edit that adds a delegation tier marker ([T0]..[T5], including
the [wip T2] / [verify T3] forms) to a TODO.md unless the acting model is Fable.

Reads the hook payload on stdin; resolves the model from the transcript's most
recent assistant message. Emits nothing and exits 0 when the write is allowed.

Usage: rank-requires-fable.sh   (no arguments; stdin is the hook JSON)
EOF
}

case "${1:-}" in
    -h|--help) usage; exit 0 ;;
esac

input=$(cat)

file=$(echo "$input" | jq -r '.tool_input.file_path // empty')
[[ "$file" == *TODO.md ]] || exit 0

# A TODO.md under templates/ is documentation, not a backlog: the skeleton
# documents the tier grammar and necessarily contains example markers like
# [T4] / [wip T2]. Those are not rankings, so they must not trip the guard.
# (Found by the guard itself, which blocked the template being written.)
case "$file" in
    */templates/*) exit 0 ;;
esac

# --- resolve the acting model from the transcript -------------------------
transcript=$(echo "$input" | jq -r '.transcript_path // empty')
[[ -n "$transcript" && -f "$transcript" ]] || exit 0   # fail open

model=$(tac "$transcript" 2>/dev/null \
        | jq -r 'select(.type=="assistant") | .message.model // empty' 2>/dev/null \
        | head -1 || true)
[[ -n "$model" ]] || exit 0                            # fail open

# Fable in any spelling (claude-fable-5, fable, fable[1m], ...) is allowed.
if echo "$model" | grep -qiE 'fable'; then
    exit 0
fi

# --- would this operation ADD a tier? -------------------------------------
# A tier is only a *ranking* when it is the marker of a list item at line start.
# Anchoring matters: every TODO.md scaffolded from the template documents the
# grammar in its header ("tier last — `[T4]`, `[wip T2]`, `[verify T3]`"), and an
# unanchored pattern counted those three as three new rankings and denied the
# write. Markdown table rows (`| \`- [T4]\` | … |`) are excluded for the same
# reason — they start with `|`, not a bullet.
TIER='^[[:space:]]*[-*] \[(x|X|wip|verify)?[[:space:]]*T[0-5][[:space:]]*\]'

# `grep` exits 1 on no-match, which under `set -o pipefail` fails the whole
# pipeline. Guard the grep itself with `|| true` — putting `|| echo 0` after
# `wc -l` instead yields the string "0\n0", since wc already printed its own 0.
count() { { grep -cE "$TIER" <<<"${1:-}" || true; } | head -1; }

tool=$(echo "$input" | jq -r '.tool_name // empty')
case "$tool" in
    Edit)
        before=$(count "$(echo "$input" | jq -r '.tool_input.old_string // empty')")
        after=$(count "$(echo "$input" | jq -r '.tool_input.new_string // empty')")
        ;;
    Write)
        before=$([[ -f "$file" ]] && count "$(cat "$file")" || echo 0)
        after=$(count "$(echo "$input" | jq -r '.tool_input.content // empty')")
        ;;
    *) exit 0 ;;
esac

[[ "$after" -gt "$before" ]] || exit 0

jq -n --arg model "$model" --arg n "$((after - before))" '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: "deny",
    permissionDecisionReason: (
      "Ranking is T5 — only Fable assigns delegation tiers, and it is never delegated. "
      + "This write adds " + $n + " tier marker(s) to a TODO.md while the acting model is "
      + $model + ".\n\n"
      + "If you are the orchestrator: switch with /model fable, then retry.\n"
      + "If you are a subagent: do NOT rank. Preserve existing tiers exactly, leave "
      + "untiered items untiered, and report them back so the orchestrator ranks them.\n\n"
      + "Moving or reformatting existing tiers is allowed — only adding a new one is blocked. "
      + "See ~/CLAUDE.md — Delegation."
    )
  }
}'
