#!/usr/bin/env bash
# Generated by python-tui-lib/scripts/bundle-tiered-todo.sh — DO NOT EDIT.
# Source: ~/python-tui-lib/hooks/todo-conformance.sh
# PostToolUse[Write|Edit] — report TODO.md conformance drift.
#
# `/todo` has always told models "the PostToolUse hook will block the write if
# you leave an [x] in ## Open". That was true in exactly ONE project of 26
# (foundrylinux.org's project-local check-todo-done.sh) and false everywhere
# else. This makes the claim true globally.
#
# BLOCKING on errors, advisory on warnings. It shipped advisory because 10 of
# the 26 TODO.md files were still legacy flat format and a blocking hook would
# have failed every write to them; all 26 were swept the same day and the tree
# reached zero errors, which was the agreed gate for turning it on.
#
# Errors are structural and always fixable: a stray [x] outside ## Done, an
# unranked open item, a missing bucket, a tier on a Watch/Parked bullet.
# Warnings stay advisory because several are legitimately unfixable — a Done
# line with no date, plan or commit to derive one from cannot be put in
# canonical form without inventing data, and inventing it is worse.
#
# A file with a deliberate house convention opts out per-check with
# `<!-- todo-lint: disable=stray-done -->`; llvm-mos-65816 uses exactly that.
#
# foundrylinux.org keeps its own stricter blocking hook — this does not replace
# it. Trading a working guard for a weaker advisory one would be a regression.
set -euo pipefail

case "${1:-}" in
    -h|--help)
        cat <<'EOF'
todo-conformance.sh — PostToolUse[Write|Edit] advisory TODO.md linter

Runs todo-lint.py against any TODO.md that was just written, and reports
findings back to the model as context. Never blocks (today).

Usage: todo-conformance.sh   (no arguments; stdin is the hook JSON)
EOF
        exit 0
        ;;
esac

input=$(cat)
file=$(echo "$input" | jq -r '.tool_input.file_path // empty')

[[ "$file" == *TODO.md ]] || exit 0
[[ -f "$file" ]] || exit 0
case "$file" in */templates/*) exit 0 ;; esac   # templates document the grammar

# Resolve the linter in either layout: installed as a plugin (CLAUDE_PLUGIN_ROOT
# is set and the bundle carries its own scripts/ + lib/), or running live out of
# ~/python-tui-lib. A consumer who installs only the plugin has no ~/python-tui-lib.
LINT=""
for cand in "${CLAUDE_PLUGIN_ROOT:-}/scripts/todo-lint.py" \
            "$HOME/python-tui-lib/scripts/todo-lint.py"; do
    [[ -f "$cand" ]] && { LINT="$cand"; break; }
done
[[ -n "$LINT" ]] || exit 0

# The linter exits 1 when it found ERRORS, 0 for warnings-only or clean. Capture
# the status without letting `set -e` kill the hook.
out=$(python3 "$LINT" --quiet "$file" 2>&1) && status=0 || status=$?
[[ -n "$out" ]] || exit 0

if [[ "$status" -ne 0 ]]; then
    printf 'TODO.md conformance FAILED — fix before continuing (see ~/CLAUDE.md — Delegation, and /todo Format rules):\n%s\n' "$out" >&2
    printf '\nMechanical fixes: python3 %s --fix %q\nDeliberate house convention: add <!-- todo-lint: disable=<check> --> to the file.\n' "$LINT" "$file" >&2
    exit 2
fi

printf 'TODO.md conformance (warnings only — advisory):\n%s\n' "$out" >&2
exit 0
