#!/usr/bin/env bash
# Generated by python-tui-lib/scripts/bundle-tiered-todo.sh — DO NOT EDIT.
# Source: ~/python-tui-lib/hooks/todo-reminder.sh
# Stop hook — surface open TODO items so "what's next?" pulls from the backlog.
#
# Matches every still-to-do marker, not just `- [ ]`:
#   - [ ]          open, unranked (dispatched at the T3 default)
#   - [T4]         open, tier 4
#   - [wip T2]     in progress
#   - [verify T3]  awaiting verification
# `- [x]` is excluded — 'x' is not in the status alternation, so a Done line
# fails the trailing `\]` match.
#
# Keep in sync with TASK_RE in tuilib/todo_format.py, which is canonical.
#
# The payload is built with `jq -n --arg`, NOT printf. The previous printf form
# interpolated multi-line grep output straight into a JSON string literal, so
# every emission carried raw newlines and was rejected as invalid JSON — this
# hook silently did nothing from the day it was written. jq does the escaping.
set -euo pipefail

root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
todos=$(grep -m5 -E '^- \[[[:space:]]*(wip|verify)?[[:space:]]*(T[0-5])?[[:space:]]*\]' \
    "$root/TODO.md" 2>/dev/null | cut -c1-120) || true

[[ -n "$todos" ]] || exit 0

jq -n --arg todos "$todos" '{
  hookSpecificOutput: {
    additionalContext: (
      "When suggesting next steps, reference open TODO items. The bracket carries status and delegation tier — dispatch each to its tier agent (unranked = T3); see ~/CLAUDE.md — Delegation:\n"
      + $todos
    )
  }
}'
