#!/usr/bin/env bash
# generate-repology-ruleset.sh — emit the github.com/repology/repology-rules YAML
# for this repo, derived from each packages/*/debian/control's `X-Repology-Project`
# field (the same field that drives the apt-index badge via gen-index.py).
#
# Repology *producer* onboarding: once you submit a repos.d/deb/{{REPO_NAME}}.yaml
# entry to repology-updater (tagging packages `ruleset: [debuntu, {{REPO_NAME}}]`),
# these rules map our names to canonical Repology projects. Every rule is scoped
# `ruleset: {{REPO_NAME}}` so it ONLY affects this repo (an unscoped setname would
# rewrite every distro's package of the same name).
#
# Classification, per Source stanza (publish a Sources index → Repology matches
# SOURCE names via DebianSourcesParser):
#   X-Repology-Project: <proj>, proj != source  → setname (remap to canonical project)
#   X-Repology-Project: <proj>, proj == source  → nothing (Repology defaults to the name)
#   X-Repology-Project: none                     → remove (your own / not-on-Repology)
#   no X-Repology-Project (metapackages)         → remove (not a real upstream project)
#
# Usage: generate-repology-ruleset.sh [-o <file>]   (default: stdout)
set -euo pipefail

OUT=""
case "${1:-}" in
    -h|--help)
        echo "Usage: $(basename "$0") [-o <file>]"
        echo "Emit the repology-rules YAML (ruleset: {{REPO_NAME}}) from packages/*/debian/control"
        echo "X-Repology-Project fields. Default output: stdout."
        exit 0 ;;
    -o) OUT="${2:?-o needs a path}" ;;
    "") ;;
    *) echo "ERROR: unknown arg: $1 (try --help)" >&2; exit 2 ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGES_DIR="$(cd "$SCRIPT_DIR/.." && pwd)/packages"
RULESET="{{REPO_NAME}}"

remaps=()        # "source<TAB>project" where they differ
ignore_meta=()   # no X-Repology-Project field → authored metapackage
ignore_none=()   # X-Repology-Project: none → real tool, not on Repology

for ctrl in "$PACKAGES_DIR"/*/debian/control; do
    [[ -f "$ctrl" ]] || continue
    src="$(grep -m1 '^Source:' "$ctrl" | awk '{print $2}' || true)"
    [[ -n "$src" ]] || continue
    proj="$(grep -m1 '^X-Repology-Project:' "$ctrl" | sed 's/^X-Repology-Project:[[:space:]]*//' || true)"
    if [[ -z "$proj" ]]; then
        ignore_meta+=("$src")
    elif [[ "${proj,,}" == "none" ]]; then
        ignore_none+=("$src")
    elif [[ "$proj" != "$src" ]]; then
        remaps+=("$src	$proj")
    fi
done

yaml_names() { printf '%s\n' "$@" | sort -u | paste -sd, - | sed 's/,/, /g'; }

emit() {
    echo "# {{REPO_NAME}}.yaml — Repology rules for this repo."
    echo "# GENERATED by scripts/generate-repology-ruleset.sh from each"
    echo "# packages/*/debian/control X-Repology-Project field — do not hand-edit; regenerate."
    echo "#"
    echo "# Submit to github.com/repology/repology-rules. Every rule is scoped 'ruleset: $RULESET'."
    echo

    if (( ${#remaps[@]} )); then
        echo "# ── name remaps: our source package → canonical Repology project ──"
        while IFS=$'\t' read -r src proj; do
            [[ -n "$src" ]] || continue
            printf -- "- { ruleset: %s, name: [%s], setname: \"%s\" }\n" "$RULESET" "$src" "$proj"
        done < <(printf '%s\n' "${remaps[@]}" | sort -u)
        echo
    fi

    if (( ${#ignore_meta[@]} )); then
        echo "# ── remove: authored metapackages (not real upstream projects) ──"
        printf -- "- { ruleset: %s, remove: true, name: [%s] }\n" "$RULESET" "$(yaml_names "${ignore_meta[@]}")"
        echo
    fi

    if (( ${#ignore_none[@]} )); then
        echo "# ── remove: tools verified not tracked on Repology (X-Repology-Project: none) ──"
        printf -- "- { ruleset: %s, remove: true, name: [%s] }\n" "$RULESET" "$(yaml_names "${ignore_none[@]}")"
    fi
}

if [[ -n "$OUT" ]]; then
    emit > "$OUT"
    echo "✓ wrote $OUT  (${#remaps[@]} remap, ${#ignore_meta[@]} metapackage-ignore, ${#ignore_none[@]} none-ignore)" >&2
else
    emit
fi
